// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gebkydsziiabwtbxxerw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlYmt5ZHN6aWlhYnd0Ynh4ZXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDYxNTQsImV4cCI6MjA2NzY4MjE1NH0.3dkVGuLsXDyRNpTvaaarkrZEDWuLvXXP5rAhdEofrlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});