// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcudzcqmoisxjvqcrjrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjdWR6Y3Ftb2lzeGp2cWNyanJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjEwNTEsImV4cCI6MjA2OTUzNzA1MX0.uAJJLJkCzrZxu8jOUxTEcsbwMJ_WuN137KsdaZXj-lE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});